/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TeacherAssignmentsRouteImport } from './routes/teacher-assignments'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as MyGroupsRouteImport } from './routes/my-groups'
import { Route as MyGradesRouteImport } from './routes/my-grades'
import { Route as MyBulletinRouteImport } from './routes/my-bulletin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportsRouteImport } from './routes/imports'
import { Route as GradesRouteImport } from './routes/grades'
import { Route as ExportsRouteImport } from './routes/exports'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as BulletinsRouteImport } from './routes/bulletins'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AbsencesRouteImport } from './routes/absences'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAssignmentsRoute = TeacherAssignmentsRouteImport.update({
  id: '/teacher-assignments',
  path: '/teacher-assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const MyGroupsRoute = MyGroupsRouteImport.update({
  id: '/my-groups',
  path: '/my-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const MyGradesRoute = MyGradesRouteImport.update({
  id: '/my-grades',
  path: '/my-grades',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBulletinRoute = MyBulletinRouteImport.update({
  id: '/my-bulletin',
  path: '/my-bulletin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportsRoute = ImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesRoute = GradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportsRoute = ExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const BulletinsRoute = BulletinsRouteImport.update({
  id: '/bulletins',
  path: '/bulletins',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AbsencesRoute = AbsencesRouteImport.update({
  id: '/absences',
  path: '/absences',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/absences': typeof AbsencesRoute
  '/assignments': typeof AssignmentsRoute
  '/bulletins': typeof BulletinsRoute
  '/curriculum': typeof CurriculumRoute
  '/dashboard': typeof DashboardRoute
  '/exports': typeof ExportsRoute
  '/grades': typeof GradesRoute
  '/imports': typeof ImportsRoute
  '/login': typeof LoginRoute
  '/my-bulletin': typeof MyBulletinRoute
  '/my-grades': typeof MyGradesRoute
  '/my-groups': typeof MyGroupsRoute
  '/students': typeof StudentsRoute
  '/teacher-assignments': typeof TeacherAssignmentsRoute
  '/users': typeof UsersRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/': typeof GroupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/absences': typeof AbsencesRoute
  '/assignments': typeof AssignmentsRoute
  '/bulletins': typeof BulletinsRoute
  '/curriculum': typeof CurriculumRoute
  '/dashboard': typeof DashboardRoute
  '/exports': typeof ExportsRoute
  '/grades': typeof GradesRoute
  '/imports': typeof ImportsRoute
  '/login': typeof LoginRoute
  '/my-bulletin': typeof MyBulletinRoute
  '/my-grades': typeof MyGradesRoute
  '/my-groups': typeof MyGroupsRoute
  '/students': typeof StudentsRoute
  '/teacher-assignments': typeof TeacherAssignmentsRoute
  '/users': typeof UsersRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups': typeof GroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/absences': typeof AbsencesRoute
  '/assignments': typeof AssignmentsRoute
  '/bulletins': typeof BulletinsRoute
  '/curriculum': typeof CurriculumRoute
  '/dashboard': typeof DashboardRoute
  '/exports': typeof ExportsRoute
  '/grades': typeof GradesRoute
  '/imports': typeof ImportsRoute
  '/login': typeof LoginRoute
  '/my-bulletin': typeof MyBulletinRoute
  '/my-grades': typeof MyGradesRoute
  '/my-groups': typeof MyGroupsRoute
  '/students': typeof StudentsRoute
  '/teacher-assignments': typeof TeacherAssignmentsRoute
  '/users': typeof UsersRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/': typeof GroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/absences'
    | '/assignments'
    | '/bulletins'
    | '/curriculum'
    | '/dashboard'
    | '/exports'
    | '/grades'
    | '/imports'
    | '/login'
    | '/my-bulletin'
    | '/my-grades'
    | '/my-groups'
    | '/students'
    | '/teacher-assignments'
    | '/users'
    | '/groups/$groupId'
    | '/groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/absences'
    | '/assignments'
    | '/bulletins'
    | '/curriculum'
    | '/dashboard'
    | '/exports'
    | '/grades'
    | '/imports'
    | '/login'
    | '/my-bulletin'
    | '/my-grades'
    | '/my-groups'
    | '/students'
    | '/teacher-assignments'
    | '/users'
    | '/groups/$groupId'
    | '/groups'
  id:
    | '__root__'
    | '/'
    | '/absences'
    | '/assignments'
    | '/bulletins'
    | '/curriculum'
    | '/dashboard'
    | '/exports'
    | '/grades'
    | '/imports'
    | '/login'
    | '/my-bulletin'
    | '/my-grades'
    | '/my-groups'
    | '/students'
    | '/teacher-assignments'
    | '/users'
    | '/groups/$groupId'
    | '/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbsencesRoute: typeof AbsencesRoute
  AssignmentsRoute: typeof AssignmentsRoute
  BulletinsRoute: typeof BulletinsRoute
  CurriculumRoute: typeof CurriculumRoute
  DashboardRoute: typeof DashboardRoute
  ExportsRoute: typeof ExportsRoute
  GradesRoute: typeof GradesRoute
  ImportsRoute: typeof ImportsRoute
  LoginRoute: typeof LoginRoute
  MyBulletinRoute: typeof MyBulletinRoute
  MyGradesRoute: typeof MyGradesRoute
  MyGroupsRoute: typeof MyGroupsRoute
  StudentsRoute: typeof StudentsRoute
  TeacherAssignmentsRoute: typeof TeacherAssignmentsRoute
  UsersRoute: typeof UsersRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-assignments': {
      id: '/teacher-assignments'
      path: '/teacher-assignments'
      fullPath: '/teacher-assignments'
      preLoaderRoute: typeof TeacherAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-groups': {
      id: '/my-groups'
      path: '/my-groups'
      fullPath: '/my-groups'
      preLoaderRoute: typeof MyGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-grades': {
      id: '/my-grades'
      path: '/my-grades'
      fullPath: '/my-grades'
      preLoaderRoute: typeof MyGradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bulletin': {
      id: '/my-bulletin'
      path: '/my-bulletin'
      fullPath: '/my-bulletin'
      preLoaderRoute: typeof MyBulletinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imports': {
      id: '/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof ImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades': {
      id: '/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof GradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exports': {
      id: '/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof ExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulletins': {
      id: '/bulletins'
      path: '/bulletins'
      fullPath: '/bulletins'
      preLoaderRoute: typeof BulletinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/absences': {
      id: '/absences'
      path: '/absences'
      fullPath: '/absences'
      preLoaderRoute: typeof AbsencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbsencesRoute: AbsencesRoute,
  AssignmentsRoute: AssignmentsRoute,
  BulletinsRoute: BulletinsRoute,
  CurriculumRoute: CurriculumRoute,
  DashboardRoute: DashboardRoute,
  ExportsRoute: ExportsRoute,
  GradesRoute: GradesRoute,
  ImportsRoute: ImportsRoute,
  LoginRoute: LoginRoute,
  MyBulletinRoute: MyBulletinRoute,
  MyGradesRoute: MyGradesRoute,
  MyGroupsRoute: MyGroupsRoute,
  StudentsRoute: StudentsRoute,
  TeacherAssignmentsRoute: TeacherAssignmentsRoute,
  UsersRoute: UsersRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  GroupsIndexRoute: GroupsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
